# Generated by Django 5.0.1 on 2024-05-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='available_seats',
            new_name='passengers',
        ),
    ]
